In [1]:
!pip install faker pandas numpy

Collecting faker
  Downloading faker-40.11.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.11.1-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.4 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.11.1

Adding randomness and creating template for datasets

In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random

fake = Faker()

random.seed(42)
np.random.seed(42)
Faker.seed(42)

CITIES = ["Bangalore", "Mumbai", "Delhi", "Chennai", "Hyderabad", "Pune", "Kolkata"]

def generate_clean_data(n_rows=50):
    data = []

    for _ in range(n_rows):
        row = {
            "name": fake.name(),
            "age": random.randint(18, 70),
            "email": fake.email(),
            "city": random.choice(CITIES),
            "salary": round(random.uniform(20000, 100000), 2)
        }
        data.append(row)

    df = pd.DataFrame(data)

    return df

In [3]:
df_clean = generate_clean_data(20)

df_clean.head()

              name  age                      email       city    salary
0     Allison Hill   58   donaldgarcia@example.net  Bangalore  22000.86
1  Angie Henderson   35     davisjesse@example.net     Mumbai  37856.86
2  Cristian Santos   65      lrobinson@example.com  Bangalore  74135.96
3  Abigail Shaffer   52      jpeterson@example.org  Bangalore  67239.40
4  Gabrielle Davis   20  howardmaurice@example.com  Bangalore  27495.62

Checking dataset before corruption

In [4]:
print("Missing values:\n", df_clean.isnull().sum())
print("\nDuplicates:", df_clean.duplicated().sum())
print("\nData types:\n", df_clean.dtypes)

Missing values:
 name      0
age       0
email     0
city      0
salary    0
dtype: int64

Duplicates: 0

Data types:
 name       object
age         int64
email      object
city       object
salary    float64
dtype: object

Corrupting the dataset

In [5]:
def inject_missing_values(df, fraction=0.1):
    df = df.copy()

    n_rows, n_cols = df.shape
    total_cells = n_rows * n_cols
    n_missing = int(total_cells * fraction)

    for _ in range(n_missing):
        i = random.randint(0, n_rows - 1)
        j = random.randint(0, n_cols - 1)
        df.iat[i, j] = np.nan

    return df

In [6]:
def inject_duplicates(df, fraction=0.1):
    df = df.copy()

    n_rows = df.shape[0]
    n_duplicates = int(n_rows * fraction)

    duplicate_rows = df.sample(n=n_duplicates, replace=True)

    df = pd.concat([df, duplicate_rows], ignore_index=True)

    return df

In [7]:
def corrupt_salary_format(df, fraction=0.3):
    df = df.copy()

    # Convert entire column to object first (IMPORTANT)
    df["salary"] = df["salary"].astype(object)

    indices = df.sample(frac=fraction).index

    for i in indices:
        val = df.at[i, "salary"]
        df.at[i, "salary"] = f"${val:,.2f}"

    return df

In [8]:
def corrupt_dataset(df):
    df_dirty = df.copy()

    df_dirty = inject_missing_values(df_dirty, 0.1)
    df_dirty = inject_duplicates(df_dirty, 0.1)
    df_dirty = corrupt_salary_format(df_dirty, 0.3)

    return df_dirty

Checking the dataset after corruption

In [9]:
df_dirty = corrupt_dataset(df_clean)

df_dirty.head(10)

              name   age                         email       city      salary
0     Allison Hill  58.0      donaldgarcia@example.net  Bangalore  $22,000.86
1  Angie Henderson  35.0        davisjesse@example.net     Mumbai    37856.86
2  Cristian Santos  65.0         lrobinson@example.com  Bangalore    74135.96
3  Abigail Shaffer  52.0         jpeterson@example.org  Bangalore     67239.4
4  Gabrielle Davis  20.0     howardmaurice@example.com  Bangalore    27495.62
5   Monica Herrera  32.0                           NaN        NaN     68161.5
6      Shannon Ray  53.0    williamsjeremy@example.com     Mumbai    77281.57
7              NaN  62.0             xreid@example.org  Hyderabad    53561.59
8              NaN  46.0       lynchgeorge@example.net  Hyderabad  $42,255.26
9              NaN  18.0  gabriellecameron@example.org    Kolkata  $84,465.54

In [10]:
print("Missing values:\n", df_dirty.isnull().sum())
print("\nDuplicates:", df_dirty.duplicated().sum())
print("\nData types:\n", df_dirty.dtypes)

Missing values:
 name      3
age       4
email     3
city      1
salary    0
dtype: int64

Duplicates: 2

Data types:
 name       object
age       float64
email      object
city       object
salary     object
dtype: object

Function that will be called during reset

In [11]:
def generate_episode(n_rows=50):
    # Step 1: generate clean dataset
    df_clean = generate_clean_data(n_rows)

    # Step 2: corrupt it
    df_dirty = corrupt_dataset(df_clean)

    return df_clean, df_dirty

In [12]:
for i in range(3):
    clean, dirty = generate_episode(20)

    print(f"\n--- Episode {i+1} ---")
    print("Clean shape:", clean.shape)
    print("Dirty shape:", dirty.shape)
    print("Duplicates:", dirty.duplicated().sum())

--- Episode 1 ---
Clean shape: (20, 5)
Dirty shape: (22, 5)
Duplicates: 1

--- Episode 2 ---
Clean shape: (20, 5)
Dirty shape: (22, 5)
Duplicates: 0

--- Episode 3 ---
Clean shape: (20, 5)
Dirty shape: (22, 5)
Duplicates: 1

In [13]:
def run_pipeline(num_runs=5):
    for i in range(num_runs):
        clean, dirty = generate_episode(20)

        print(f"\n=== Run {i+1} ===")
        print("Dirty dataset preview:")
        print(dirty.head(3))
run_pipeline(3)

=== Run 1 ===
Dirty dataset preview:
                name   age                        email       city      salary
0                NaN  33.0   elliottjeffery@example.net  Hyderabad    67561.53
1                NaN  57.0  stricklandfrank@example.com  Bangalore  $53,537.99
2  Alexander Collins  55.0         tsanders@example.org  Hyderabad    61822.62

=== Run 2 ===
Dirty dataset preview:
             name  age                      email       city    salary
0  Jennifer Jones   22  hernandezlisa@example.com       Pune  92314.29
1     David Grant   52        yobrien@example.net  Bangalore   86767.6
2    Joseph Hayes   55                        NaN  Hyderabad   31847.5

=== Run 3 ===
Dirty dataset preview:
            name   age                        email       city      salary
0  Thomas Romero  45.0     michellehill@example.com      Delhi     78283.6
1  Richard Adams   NaN  campbellkenneth@example.net    Chennai  $68,496.71
2    Mary Grimes  50.0                          NaN  Bangalore  $50,815.63

testing

In [14]:
generate_episode()

(                  name  age                        email       city    salary
 0      Patricia Becker   67   courtneyberger@example.net  Bangalore  56433.29
 1      Richard Johnson   58        jessica14@example.com  Hyderabad  35554.82
 2       Casey Anderson   62         alyssa42@example.com    Chennai  59550.17
 3         Terry Coffey   33          julie51@example.com     Mumbai  72484.64
 4          Brenda Levy   18          zcoffey@example.net    Kolkata  88835.25
 5        Richard Smith   24      gibsonemily@example.net    Kolkata  54011.70
 6         James Little   29         daniel37@example.org    Kolkata  96637.28
 7         Terri Murphy   51      deborahreid@example.com    Chennai  24017.47
 8      Elizabeth Ortiz   33   brandonjohnson@example.com    Kolkata  29708.69
 9         David Medina   26          qchavez@example.net    Kolkata  57171.46
 10   Kimberly Matthews   51       nicolepena@example.com  Hyderabad  67636.19
 11      Teresa Ramirez   66           jeff73@example.com    Chennai  69012.19
 12    Michael Stephens   64          bruce43@example.org  Hyderabad  54139.26
 13      Samantha Davis   53    darleneharper@example.org    Chennai  91776.65
 14         Gavin Zhang   65     caseyhubbard@example.org    Kolkata  57973.95
 15          Robin Hall   34  kristinacarlson@example.com    Kolkata  39779.18
 16    Brianna Anderson   58         lauren10@example.org      Delhi  81265.09
 17       Richard Young   51         alfred40@example.org    Chennai  70139.87
 18         Kelly Reese   35            xwest@example.net    Chennai  26198.67
 19         Jodi Walker   36     acostaregina@example.net     Mumbai  41737.21
 20      Judith Maynard   38      lutzmelanie@example.com  Hyderabad  26446.21
 21  Katherine Browning   27          lammarc@example.org     Mumbai  50642.82
 22      Donald Schultz   27          oscar98@example.com       Pune  37116.23
 23        Larry Garcia   44     farrelldebra@example.net    Chennai  46470.51
 24         Cindy Hayes   47     robertwilcox@example.com    Chennai  24981.26
 25     Brandon Simmons   44       nicholas27@example.org    Chennai  92387.08
 26    Bradley Reynolds   55           lisa80@example.net       Pune  21562.56
 27   Kristina Santiago   66           qgomez@example.com  Hyderabad  50430.48
 28    Michelle Schmitt   18        michael98@example.org      Delhi  43889.01
 29          John Boone   42          megan51@example.com    Kolkata  91331.32
 30         Renee Bruce   44       lynchdiane@example.net  Hyderabad  79801.25
 31    Christopher Park   52         sandra50@example.org    Kolkata  68260.21
 32       Kylie Morales   32     joycebonilla@example.org    Chennai  37553.73
 33        Cindy Barnes   45           eric45@example.net    Chennai  22321.99
 34        Sophia Moore   39      craigjoseph@example.net       Pune  74331.35
 35      Lawrence Perry   43       kariwilson@example.com       Pune  33203.58
 36     Michael Watkins   47        brandon69@example.org     Mumbai  98457.76
 37          Eric Clark   52   kathrynroberts@example.org  Bangalore  92554.31
 38       Paul Thompson   55           opatel@example.net  Hyderabad  73039.98
 39          Mary Gomez   23         chensley@example.com       Pune  54289.02
 40       Thomas Atkins   47           tberry@example.net     Mumbai  24022.77
 41         Brian Smith   42         george97@example.net      Delhi  36932.82
 42       Anita Richard   38      ryanmorales@example.org      Delhi  80898.38
 43         Eric Morgan   42       kimberly18@example.net      Delhi  80160.79
 44      Jordan Bullock   44        michael23@example.org      Delhi  86792.87
 45      Craig Morrison   48   thompsonkendra@example.com  Bangalore  79921.94
 46        Justin Riley   21       michelle52@example.com      Delhi  37937.77
 47       Jeremy Turner   22       brittany58@example.org    Kolkata  96582.85
 48         Jesse Brown   20          chase19@example.net    Kolkata  22482.40
 49       Julie Spencer   33         colelisa@example.net     Mumbai  87138.31,
                   name   age                        email       city  \
 0      Patricia Becker  67.0   courtneyberger@example.net        NaN
 1      Richard Johnson  58.0        jessica14@example.com  Hyderabad
 2       Casey Anderson  62.0                          NaN    Chennai
 3         Terry Coffey  33.0          julie51@example.com     Mumbai
 4          Brenda Levy  18.0          zcoffey@example.net    Kolkata
 5        Richard Smith  24.0      gibsonemily@example.net    Kolkata
 6         James Little  29.0                          NaN    Kolkata
 7         Terri Murphy  51.0      deborahreid@example.com    Chennai
 8      Elizabeth Ortiz  33.0   brandonjohnson@example.com    Kolkata
 9         David Medina  26.0          qchavez@example.net    Kolkata
 10   Kimberly Matthews  51.0       nicolepena@example.com  Hyderabad
 11      Teresa Ramirez  66.0           jeff73@example.com    Chennai
 12    Michael Stephens  64.0          bruce43@example.org  Hyderabad
 13      Samantha Davis  53.0    darleneharper@example.org    Chennai
 14         Gavin Zhang  65.0     caseyhubbard@example.org    Kolkata
 15          Robin Hall   NaN  kristinacarlson@example.com    Kolkata
 16    Brianna Anderson  58.0         lauren10@example.org      Delhi
 17       Richard Young  51.0         alfred40@example.org    Chennai
 18         Kelly Reese  35.0            xwest@example.net    Chennai
 19                 NaN  36.0     acostaregina@example.net     Mumbai
 20      Judith Maynard  38.0      lutzmelanie@example.com  Hyderabad
 21  Katherine Browning  27.0          lammarc@example.org     Mumbai
 22      Donald Schultz  27.0          oscar98@example.com       Pune
 23        Larry Garcia  44.0     farrelldebra@example.net    Chennai
 24         Cindy Hayes  47.0     robertwilcox@example.com    Chennai
 25     Brandon Simmons   NaN       nicholas27@example.org    Chennai
 26    Bradley Reynolds  55.0           lisa80@example.net       Pune
 27   Kristina Santiago  66.0           qgomez@example.com  Hyderabad
 28    Michelle Schmitt  18.0        michael98@example.org      Delhi
 29          John Boone  42.0                          NaN    Kolkata
 30                 NaN  44.0       lynchdiane@example.net  Hyderabad
 31    Christopher Park  52.0         sandra50@example.org    Kolkata
 32       Kylie Morales  32.0     joycebonilla@example.org    Chennai
 33        Cindy Barnes  45.0           eric45@example.net    Chennai
 34        Sophia Moore  39.0      craigjoseph@example.net        NaN
 35      Lawrence Perry  43.0       kariwilson@example.com       Pune
 36     Michael Watkins   NaN        brandon69@example.org     Mumbai
 37                 NaN  52.0   kathrynroberts@example.org  Bangalore
 38                 NaN  55.0           opatel@example.net  Hyderabad
 39          Mary Gomez   NaN         chensley@example.com       Pune
 40       Thomas Atkins  47.0           tberry@example.net     Mumbai
 41         Brian Smith  42.0                          NaN      Delhi
 42       Anita Richard  38.0                          NaN      Delhi
 43         Eric Morgan  42.0       kimberly18@example.net        NaN
 44      Jordan Bullock   NaN        michael23@example.org      Delhi
 45      Craig Morrison  48.0   thompsonkendra@example.com  Bangalore
 46        Justin Riley  21.0       michelle52@example.com      Delhi
 47       Jeremy Turner  22.0       brittany58@example.org    Kolkata
 48         Jesse Brown  20.0          chase19@example.net    Kolkata
 49       Julie Spencer   NaN                          NaN     Mumbai
 50      Jordan Bullock   NaN        michael23@example.org      Delhi
 51       Richard Smith  24.0      gibsonemily@example.net    Kolkata
 52   Kristina Santiago  66.0           qgomez@example.com  Hyderabad
 53   Kristina Santiago  66.0           qgomez@example.com  Hyderabad
 54         Eric Morgan  42.0       kimberly18@example.net        NaN

         salary
 0     56433.29
 1     35554.82
 2     59550.17
 3   $72,484.64
 4          NaN
 5      54011.7
 6     96637.28
 7          NaN
 8     29708.69
 9   $57,171.46
 10         NaN
 11    69012.19
 12    54139.26
 13  $91,776.65
 14    57973.95
 15  $39,779.18
 16    81265.09
 17    70139.87
 18  $26,198.67
 19         NaN
 20  $26,446.21
 21  $50,642.82
 22  $37,116.23
 23    46470.51
 24    24981.26
 25    92387.08
 26    21562.56
 27    50430.48
 28    43889.01
 29    91331.32
 30  $79,801.25
 31    68260.21
 32    37553.73
 33  $22,321.99
 34    74331.35
 35    33203.58
 36    98457.76
 37    92554.31
 38    73039.98
 39  $54,289.02
 40    24022.77
 41    36932.82
 42    80898.38
 43         NaN
 44  $86,792.87
 45    79921.94
 46  $37,937.77
 47    96582.85
 48     22482.4
 49    87138.31
 50    86792.87
 51  $54,011.70
 52  $50,430.48
 53    50430.48
 54        $nan  )

In [15]:
def analyze_issues(df):
    issues = {}

    issues["missing"] = df.isnull().sum().sum()
    issues["duplicates"] = df.duplicated().sum()
    issues["salary_format"] = df["salary"].apply(lambda x: isinstance(x, str)).sum()

    return issues

reward systen

In [16]:
def compute_reward(before_df, after_df):

    before = analyze_issues(before_df)
    after = analyze_issues(after_df)

    reward = 0

    # Missing values improvement
    reward += (before["missing"] - after["missing"]) * 0.1

    # Duplicate improvement
    reward += (before["duplicates"] - after["duplicates"]) * 0.2

    # Salary format improvement
    reward += (before["salary_format"] - after["salary_format"]) * 0.1

    # Penalty if things got worse
    if reward < 0:
        reward -= 0.2

    return reward

In [17]:
df_before = df_dirty.copy()

df_after = apply_action(df_before, "remove_duplicates")

reward = compute_reward(df_before, df_after)

print("Reward:", reward)

NameError: name 'apply_action' is not defined

In [ ]:
df_before = df_dirty.copy()

df_step1 = apply_action(df_before, "remove_duplicates")
print("Reward step 1:", compute_reward(df_before, df_step1))

df_step2 = apply_action(df_step1, "fill_missing_values")
print("Reward step 2:", compute_reward(df_step1, df_step2))

df_step3 = apply_action(df_step2, "fix_salary_format")
print("Reward step 3:", compute_reward(df_step2, df_step3))